// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductApiServiceClient is the client API for ProductApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductApiServiceClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type productApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductApiServiceClient(cc grpc.ClientConnInterface) ProductApiServiceClient {
	return &productApiServiceClient{cc}
}

func (c *productApiServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/user.api.ProductApiService/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductApiServiceServer is the server API for ProductApiService service.
// All implementations must embed UnimplementedProductApiServiceServer
// for forward compatibility
type ProductApiServiceServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedProductApiServiceServer()
}

// UnimplementedProductApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductApiServiceServer struct {
}

func (UnimplementedProductApiServiceServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedProductApiServiceServer) mustEmbedUnimplementedProductApiServiceServer() {}

// UnsafeProductApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductApiServiceServer will
// result in compilation errors.
type UnsafeProductApiServiceServer interface {
	mustEmbedUnimplementedProductApiServiceServer()
}

func RegisterProductApiServiceServer(s grpc.ServiceRegistrar, srv ProductApiServiceServer) {
	s.RegisterService(&ProductApiService_ServiceDesc, srv)
}

func _ProductApiService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductApiServiceServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.api.ProductApiService/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductApiServiceServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductApiService_ServiceDesc is the grpc.ServiceDesc for ProductApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.api.ProductApiService",
	HandlerType: (*ProductApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _ProductApiService_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/product/v1/product-api.proto",
}
