version: 3

auth:
  user_info_key: "x-user-info"
  session_key: "x-session-id"
database:
  dsn: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"
  dbname: "user-api"
  host: "62.84.127.244"
  port: "5432"
  user: "user-api"
  password: "password"
  ssl: "disable"
s3:
  bucket_name: "alexeyzer-static-files"
  id: "id_secret"
  key: "key_secret"
  endpoint: "https://storage.yandexcloud.net"
  region: "ru-central1"
app:
  http_port: "8080"
  grpc_port: "8082"
grpc:
  user_api: "62.84.114.46:8082"